version: '3.8'

services:
  app: 
    build: 
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: tray_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: tray_mysql
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: tray_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
